#Text for TCA Module:


#Gui of Main page

MainpageText = [
    _("Economic analysis"),
    _("Investment"),
    _("Energy and operating costs"),
    _("Contingencies"),
    _("Non reoccurring costs"),
    _("TOTAL COST ASSESSMENT"),
    _("GENERAL ECONOMIC DATA"),
    _("Interests"),
    _("“Loan interest rate"),
    _("%/a"),  		#percents per annual 
    _("Company specific discount rate"),
    _("Development of energy prices"),
    _("%/a of the current energy price (including Grid fee, excluding VAT)"),
    _("Choose time frame for economic"),
    _("years"),				 
    _("This timeframe will be applied to each equipment of all of the proposals. If you think there would be some maintenance or re-investment caused by this time frame, please fill in the Contingencies"),
    _("Go to the result"),
]

#GUI of Automatic mode

AutomaticInvestmentText = [
    _("INVESTMENT"),
    _("AUTOMATIC CALCULATION"),
    _("If the new process will be applied, would there be any revenue for the replacement of your existing equipments?"),
    _("If yes, please click on "Add revenue" of respective proposal to indicate the revenue(s)"),
    _("If no, please directly go to the result"),
    _("Proposal "),                # do not repeat for proposal 1, 2, 3,4 
    _("Add revenue"),
    _("go to the result"),
    _("REVENUE FROM REPLACED EQUIPMENTS"),
    _("fixed sum"),				#do not put the units (€, %) in the translation
    _("or"),
    _("percentage of initial investment"),
    _("percentage of current book value"),
    _("indicate the initial investment"),
    _("indicate the book value"),
    _("Initial investment of replaced equipments"),
    _("Initial investment"),
    _("Depreciation period"),
    _("Remaining period"),
    _("years"),
    _("Purchased Equipment"),
    _("Boiler"),
    _("Utility Connections/ System, Hydraulics"),
    _("Buildings"),
    _("Legend"),
    _("Including"),
    _("process energy generation equipment"),
    _("equipment for energy generation and transformation"),
    _("equipment for energy recovery"),
    _("equipment for cooling/recooling/closure of cooling cycles"),
    _("air condition for processes"),
    _("conduction system for energy transportation"),
    _("storage and materials handling equipment"),
    _("safety/protective equipment"),
    _("monitoring/control equipment"),
    _("laboratory/analytical equipment"),
    _("Connections/system concerning"),
    _("electricity"),
    _("steam"),
    _("water"),
    _("fuel"),
    _("plant air"),
    _("inert gas"),
    _("refrigeration"),
    _("sewerage"),
    _("general"),
    _("pumping"),
    _("Equipment"),
    _("H&C storage"),
    _("CHP"),
    _("Solar thermal"),
    _("Heat pump"),
    _("Biomass"),
    _("Chillers"),
    _("Boilers and furnaces"),
    _("HX network"),
    _("H&C distribution"),
    _("Fixed sum (EUR)"),
    _("Percentage of total investment (%)"),
    _("fundings"),
    _("Add"),
    _("remove"),
 	]

#GUI of Semi Automatic mode

SemiAutoCurrentText = [
    _("CURRENT PROCESS"),
    _("ENERGY COST"),
    _("The values come from the audit questionnaire” _ “If you would like to make any changes, please click on them"),
    _("Energy demand"),
    _("kWh/a"),
    _("Energy price (incl. Fees, excl. VAT)"),
    _("€/kWh"),
    _("Development of energy price"),
    _("%/a"),
    _("Electricity"),
    _("District heat"),
    _("Petrol"),
    _("Diesel oil"),
    _("Fossil gas"),
    _("Coal"),
    _("Biomass"),
    _("Biogas"),
    _("Other"),
    _("OPERATING AND MAINTENANCE COST"),
    _("Total operating and maintenance cost"),
    _("€/a"),
    _("This value is the total of the operating and maintenance costs given in the questionnaire. If you would like to change this value, please go back to the questionnaire module"),
    _("Go back to the main page"),
    _("Go to the next form"),
    _("CONTINGENCIES"),
    _("Do you expect future costs for perpetuating use of the current energy source in the process?"),
    _("time frame (in X years from now, X = 0 for current year)"),
    _("tax disadvantages (other than energy tax)"),
    _("obligatory provisions"),
    _("costs for remediation activities"),
    _("costs for compliance with legislation"),
    _("negative impacts on market share"),
    _("deterioration of company image"),
    _("affection by the CO2-emission trading directive"),
    _("NON RE-OCCURRING COST"),
    _("For costs occurring more than once please fill in an additional line (other cost)"),
    _("years"),
    _("indicate when presumably occurring in years after investment"),
    _("Cost"),
    _("repair works for energy equipment"),
    _("exchange of collectors"),
    _("irregular maintenance costs"),
    _("permits"),
    _("fines/penalties"),
    _("legal costs"),
    _("property/natural resource damage"),
    _("remediation costs"),
    _("clean up costs"),
    _("other treatment costs"),
    _("other prevention costs"),
    _("Revenue"),
    _("revenues for marketable permits"),
    _("other revenues"),
]

SemiAutoNewInvestmentText = [

    _("PROPOSAL"), 		 # do not repeat for proposal 1, 2, 3,4 
    _("INVESTMENT"),
    _("Total investment and fundings of the new equipments"),
    _("The values of investment are suggested by the program. If they do not apply to your process, please indicate your own values"),
    _("Investment"),
    _("Fundings"),
    _("data-based value"),
    _("User-defined values"),
    _("Percentage"),
    _("Fixed sum"),
    _("H&C storage"),
    _("CHP"),
    _("Solar thermal"),
    _("Heat pump"),
    _("Biomass"),
    _("Chillers"),
    _("Boilers and furnaces"),
    _("HX network"),
    _("H&C distribution"),
    _("REVENUE FROM REPLACED EQUIPMENTS"),
    _("If you think there would be revenue from the sale of replaced equipments, please indicate the possible value"),
    _("fixed sum"),				#do not put the units (€, %) in the translation
    _("or"),
    _("percentage of initial investment"),
    _("percentage of current book value"),
    _("indicate the initial investment"),
    _("indicate the book value"),
    _("Initial investment of replaced equipments"),
    _("Initial investment"),
    _("Depreciation period"),
    _("Remaining period"),
    _("years"),
    _("Purchased Equipment"),
    _("Boiler"),
    _("Utility Connections/ System, Hydraulics"),
    _("Buildings"),
    _("Legend"),
    _("Including"),
    _("process energy generation equipment"),
    _("equipment for energy generation and transformation"),
    _("equipment for energy recovery"),
    _("equipment for cooling/recooling/closure of cooling cycles"),
    _("air condition for processes"),
    _("conduction system for energy transportation"),
    _("storage and materials handling equipment"),
    _("safety/protective equipment"),
    _("monitoring/control equipment"),
    _("laboratory/analytical equipment"),
    _("Connections/system concerning"),
    _("electricity"),
    _("steam"),
    _("water"),
    _("fuel"),
    _("plant air"),
    _("inert gas"),
    _("refrigeration"),
    _("sewerage"),
    _("general"),
    _("pumping"),
]

SemiAutoNewEnergyOperatingText
    _("ENERGY COST"),
    _("The values come from the audit questionnaire and Einstein database"),
    _("If you would like to make any change on them, please click on the value"),
    _("Energy demand"),
    _("kWh/a"),
    _("Energy price (incl. Fees, excl. VAT)"),
    _("€/kWh"),
    _("Development of energy price"),
    _("%/a"),
    _("Electricity"),
    _("District heat"),
    _("Petrol"),
    _("Diesel oil"),
    _("Fossil gas"),
    _("Coal"),
    _("Biomass"),
    _("Biogas"),
    _("Other"),
    _("OPERATING AND MAINTENANCE COST"),
    _("If you would like to calculate the operating costs in details, please choose "Detailed operating cost calculation"),
    _("Total operating and maintenance cost"),
    _("€/a"),
    _("detailed operating cost calculation"),
    _("DETAILED OPERATING COSTS CALCULATION"),
    _("New process"),
    _("H&C storage"),
    _("CHP"),
    _("Solar thermal"),
    _("Heat pump"),
    _("Biomass"),
    _("Chillers"),
    _("Boilers and furnaces"),
    _("HX network"),
    _("H&C distribution"),
    _("Utilities"),
    _("Operating materials"),
    _("Labour"),
    _("External costs"),
    _("Regulatory compliance costs"),
    _("Insurance cost"),
    _("Future liability"),
    _("Legend"),
    _("Cost for water, plant air, inert gas, refrigerant, sewerage…"),
    _("chemicals e.g. for conditioning of boiler feed water, lubricants, cleaning materials, materials for maintenance and service"),
    _("labour for operating, on-site handling and storage, onsite pretreatment, hauling, supervision”)
        _("personnel, management personnel, maintenance personnel, energy agent, internal costs for analyses and measurements, internal costs for inspection, supervision and control..."),
    _("external maintenance personnel costs, external costs for analyses and measurements, Off-site Treatment, Off-site Disposal"),
    _("permits (if not in labour costs), mandatory trainings  (if not in labour costs), costs for mandatory monitoring and inspection (if not in labour costs), fees/taxes, reporting (if not in labour costs)"),
    _("fines/penalties, legal costs, personal injury, property/natural resource damage, remediation costs, (provisions for) clean up costs, (provisions for) treatment costs"),
]

SemiAutoNewContingNonreoccuringText=[
    _("CONTINGENCIES"),
    _("Do you expect future benefits using renewable energy?"),
    _("time frame (in X years from now, X = 0 for current year)"),
    _("tax benefits (other than energy tax)"),
    _("incentives for investment"),
    _("positive impacts on market share"),
    _("amelioration of company image"),
    _("NON RE-OCCURRING COST"),
    _("For costs occurring more than once please fill in an additional line (other cost)"),
    _("indicate when presumably occurring in years after investment"),
    _("Cost"),
    _("repair works for energy equipment"),
    _("exchange of collectors"),
    _("irregular maintenance costs"),
    _("permits"),
    _("fines/penalties"),
    _("legal costs"),
    _("property/natural resource damage"),
    _("remediation costs"),
    _("clean up costs"),
    _("other treatment costs"),
    _("other prevention costs"),
    _("Revenue"),
    _("revenues for marketable permits"),
    _("other revenues"),
]


TCAResultText=[
    _("RESULT"),
    _("Total Investment capital"),
    _("Effective Investment capital"),
    _("Benefit cost ratio (BCR)"),
    _("Payback period"),
    _("Internal Rate of Return at payback"),
    _("DIAGRAM RETURN OF INVESTMENT"),
    _("Please choose the parameters to be displayed in the diagram"),
    _("Please choose the proposal(s) to display the curves"),
    _("Go"),
    _("Net present value and internal rate of return development"),
    _("Net present values"),
    _("rate of return"),
    _("modified internal rate of return"),
    _("time [years]"),
]
