# -*- coding: cp1252 -*-
ParameterList = {
	"Code" : _("Description"),
	"ProjectCreationDate" : _("0"),
	"ProjectFinalisationDate" : _("0"),
	"LastModificationDate" : _("0"),
	"Auditor_ID" : _("Id of auditor who carryied out the audit"),
	"OriginalProjectID" : _("Original ProjectID (maybe different of actual ProjectID for imported projects)"),
	"Campaign" : _("Description of framework in which the audit was carried out (audit campaign or project)"),
	"ConfidentialityLevel" : _("0"),
	"ToolVersion" : _("0"),
	"Name" : _("name of the company"),
	"City" : _("city / country"),
	"Country" : _("0"),
	"DescripIndustry" : _("description of the industry"),
	"Branch" : _("branch"),
	"SubBranch" : _("sub-branch"),
	"NACE" : _("NACE code branch"),
	"SubNACE" : _("NACE code sub-branch"),
	"DBNaceCode_id" : _("0"),
	"Contact" : _("name of contact person"),
	"Role" : _("position of contact person in the company"),
	"Address" : _("address"),
	"Phone" : _("Telephone  No"),
	"Fax" : _("Fax No"),
	"Email" : _("E-mail"),
	"NEmployees" : _("number of employees"),
	"Turnover" : _("annual turnover"),
	"ProdCost" : _("annual production cost"),
	"BaseYear" : _("base year for economic data"),
	"Growth" : _("growth rate of the production volume foreseen for the next 5 years"),
	"Independent" : _("Is the company independent ?"),
	"OMThermal " : _("yearly O&M heat & cold"),
	"OMElectrical" : _("yearly O&M electrical "),
	"HPerDayInd" : _("total hours of operation per working day"),
	"NShifts" : _("number of shifts"),
	"NDaysInd" : _("days of production / operation per year"),
	"NoProdStart" : _("principal period of holidays or stops for maintenance - start date"),
	"NoProdStop" : _("principal period of holidays or stops for maintenance - end date"),
	"Product" : _("type of product"),
	"ProductCode" : _("product's code"),
	"QProdYear" : _("quantity of product(s) per year"),
	"ProdUnit" : _("measurement unit for product quantity"),
	"TurnoverProd" : _("annual turnover per product"),
	"NProducts" : _("Number of products"),
	"HoursInd" : _("Total yearly working hours in industry"),
	"Process" : _("process short name"),
	"DBUnitOperation_id" : _("0"),
	"UnitOperation" : _("unit operation type"),
	"ProcType" : _("process type"),
	"ProcMed" : _("product or process medium (water, oil, air, ...)"),
	"PT" : _("typical (final) temperature of the  process medium during operation"),
	"PTInFlow" : _("inlet temperature of the process medium (before heat recovery)"),
	"PTInMax" : _("maximum allowed temperature for external preheating"),
	"PTStartUp" : _("start-up temperature of process medium (after breaks)"),
	"VInFlowDay" : _("daily inflow of process medium"),
	"VolProcMed" : _("volume of the process medium within the equipment or storage"),
	"QOpProc " : _("Power requirement of the process in operation"),
	"HPerDayProc" : _("hours of process operation per day"),
	"NBatch" : _("number of batches per day"),
	"HBatch" : _("duration of 1 batch"),
	"NDaysProc" : _("days of process operation per year"),
	"ProcMedOut" : _("medium of outgoing waste heat flows"),
	"PTOutFlow" : _("temperature of outgoing (waste) heat flows"),
	"HOutFlow " : _("specific enthalpy of outgoing (waste) heat flows"),
	"PTFinal" : _("final  temperature of outgoing (waste) heat flows"),
	"VOutFlow" : _("daily outflow of process medium"),
	"HeatRecOK" : _("can heat be recovered from the outflowing medium ?"),
	"HeatRecExist" : _("Exists heat from heat  recovery for the process ?"),
	"SourceWasteHeat" : _("source of waste heat"),
	"PTInFlowRec" : _("inlet temperature of the process medium  (after heat recovery)"),
	"EnclChartHCSupply" : _("Enclosing Flowchart of HC supply system"),
	"SupplyMed" : _("Medium supplying heat or cold to the process (water, steam, air)"),
	"PipeDuctProc" : _("heat or cold supply to the process from distribution line / branch No."),
	"TSupply" : _("temperature of the incoming medium supplying heat or cold to the process/heat exchanger"),
	"SupplyMedFlow" : _("flow rate of the heat supply medium (close to process)"),
	"UPHtotQ" : _("Annual consumption of UPH"),
	"Process data. Annex: time schedules" : _("0"),
	"UPH" : _("TOTAL- Useful process heat (per process - UPHk)"),
	"UPHc" : _("circulation / renovation"),
	"UPHm" : _("maintenance"),
	"UPHs" : _("preheating at start-up"),
	"QWHProc" : _("available waste heat from processes"),
	"UPHp" : _("preheating from waste heat"),
	"UPHmin" : _("minimum required heat demand with heat recovery"),
	"ProcHC" : _("Heating (1) or Cooling (-1)"),
	"UPCtot" : _("total process cooling demand"),
	"UPCnet" : _("total process cooling demand after heat recovery"),
	"PMU" : _("measurement unit for process medium (pmu)"),
	"MProcMed" : _("yearly quantity of medimum processed"),
	"PE_SEC" : _("Specific energy consumption (primary energy)"),
	"EL_SEC" : _("Specific energy consumption (electricity)"),
	"UPH_SEC" : _("Specific energy consumption (UPH)"),
	"TEnvProc" : _("Temperature of the process environment for calculation of heat losses under operation"),
	"UAProc" : _("thermal heat loss coefficient of the process"),
	"QEvapProc " : _("Power requirement for evaporation or endothermal chemical reactions (negative for condensation or exothermal reactions)"),
	"NThProc" : _("Number of thermal processes"),
	"QdotProc_c" : _("circulation / renovation"),
	"QdotProc_m" : _("maintenance"),
	"QdotProc_s" : _("preheating at start-up"),
	"QdotProc_w" : _("waste heat recovery"),
	"HperYearProc" : _("Yearly operating hours of process=HPerDayProc*NDaysProc"),
	"QHXProcInt" : _("Heat recovered internally in each process via internal heat excanges (e.g. Pasteurisation)"),
	"UPHcGross" : _("UPHc Gross (before internal heat recovery: only circulation!)"),
	"Fuel" : _("Fuels used"),
	"FuelUnit" : _("unit"),
	"MFuelYear" : _("annual consumption"),
	"FECFuel" : _("total own fuel consumption (LCV)"),
	"FuelTariff" : _("fuel price"),
	"FuelCostYear" : _("annual energy cost"),
	"PowerContrTot" : _("contracted power"),
	"PowerContrStd" : _("Contracted power standard"),
	"PowerContrPeak" : _("Contracted power peak"),
	"PowerContrVall" : _("Contracted power valley"),
	"ElectricityTotYear" : _("annual consumption"),
	"ElectricityPeakYear" : _("Annual consumption peak"),
	"ElectricityStandYear" : _("Annual consumption standard"),
	"ElectricityValleyYear" : _("Annual consumption valley"),
	"ElectricityGen" : _("self-generation (co-generation)"),
	"ElectricitySales" : _("sales to grid (co-generation)"),
	"text for Quest." : _("Peak"),
	"text for Quest." : _("Standard"),
	"text for Quest." : _("Valley"),
	"text for Quest." : _("TOTAL"),
	"text for Quest." : _("Electric consumption according type of use"),
	"text for Quest." : _("Electricity for thermal uses"),
	"text for Quest." : _("Electricity for non-thermal uses"),
	"text for Quest." : _("Refrigeration"),
	"ElectricityRef" : _("Electricity for refrigeration"),
	"text for Quest." : _("Air Conditioning"),
	"ElectricityAC" : _("Electricity for air conditioning"),
	"text for Quest." : _("Other uses"),
	"ElectricityThOther" : _("Electricity for other thermal uses"),
	"text for Quest." : _("Motors and machines"),
	"ElectricityMotors" : _("Electricity for motors"),
	"text for Quest." : _("Electro-chemics"),
	"ElectricityChem" : _("Electricity for electro-chemical processes"),
	"text for Quest." : _("Lightning"),
	"ElectricityLight" : _("Electricity for lightning"),
	"ElTariffClassTot" : _("Tariff type / class (total)"),
	"ElTariffClassStd" : _("Tariff type / class (standard)"),
	"ElTariffClassPeak" : _("Tariff type / class (peak)"),
	"ElTariffClassTotVall" : _("Tariff type / class (valley)"),
	"ElTariffClassCHP" : _("Tariff type / class (CHP)"),
	"ElTariffPowTot" : _("Tariff on installed power (total)"),
	"ElTariffPowStd" : _("Tariff on installed power (standard)"),
	"ElTariffPowPeak" : _("Tariff on installed power (peak)"),
	"ElTariffPowVall" : _("Tariff on installed power (valley)"),
	"ElTariffPowCHP" : _("Tariff on installed power (CHP)"),
	"ElTariffCTot" : _("Tariff on consumption (total)"),
	"ElTariffCStd" : _("Tariff on consumption (standard)"),
	"ElTariffCPeak" : _("Tariff on consumption (peak)"),
	"ElTariffCVall" : _("Tariff on consumption (valley)"),
	"ETariffCHP" : _("Tariff sales of CHP (without feedin-tariff)"),
	"ElCostYearTot" : _("Annual electricity cost total"),
	"ElCostYearStd" : _("Annual electricity cost standard"),
	"ElCostYearPeak" : _("Annual electricity cost peak"),
	"ElCostYearVall" : _("Annual electricity cost valley"),
	"ElSalesYearCHP" : _("Annual electricity sales CHP"),
	"PercentElTotcost" : _("Percentage of electricity cost on overall production cost"),
	"PercentFuelTotcost" : _("Percentage of fuel cost on overall production cost"),
	"EnclMonthlyFuelBills" : _("Enclosing monthly fuel bills?"),
	"EnclMonthlyElBills" : _("Enclosing monthly electricity bills?"),
	"ElProd" : _("Electricity consumption per product"),
	"FuelProd" : _("Fuel consumption per product"),
	"FEC" : _("Final energy consumptioin total (for the analysed industry)"),
	"FET" : _("FET total (for the analysed industry)"),
	"FEO" : _("FEO total (for the analysed industry)"),
	"----FECFuel in questionnnaire---" : _("0"),
	"FETFuel" : _("total own fuel consumption (LCV)"),
	"FEOFuel" : _("total own fuel consumption (LCV)"),
	"FECel" : _("Total electricity consumed by the factory"),
	"FETel" : _("Electricity for thermal use (total industry)"),
	"FEOel" : _("Electricity for non thermal use (total industry)"),
	"PEC" : _("Primary energy consumptioin total (for the analysed industry)"),
	"PET" : _("PET total (for the analysed industry)"),
	"PEO" : _("PEO total (for the analysed industry)"),
	"PECFuel " : _("Total Primary Energy per all fuels used in industry"),
	"PETFuel" : _("Total Primary Energy per all fuels thermal use"),
	"PECel" : _("Total Primary Energy per all electricity used in industry"),
	"PETel" : _("Total Primary Energy per all electricity thermal use"),
	"FECel_EXT" : _("Total own electricity consumption extrapolated to growth of production volume"),
	"FECFuel_EXT" : _("Total own fuel consumption extrapolated to growth of production volume"),
	"PEC_EXT" : _("Total primary energy consumption extrapolated to growth of production volume"),
	"FUEL_INT" : _("Intensity of fuel consumption (LCV) on turnover"),
	"FUEL_SEC" : _("Specific energy consumption (fuel)"),
	"EL_INT" : _("Intensity of electricity consumption on turnover"),
	"EL_SEC" : _("Specific energy consumption (electricity)"),
	"PE_INT" : _("Primary energy intensity (turnover)"),
	"PE_SEC" : _("Specific energy consumption (primary energy)"),
	"FuelCode" : _("Code"),
	"NFuels" : _("Number of fuels"),
	"ELECTRICITY_Type" : _("Electricity by type of use"),
	"PEConvFuelMix" : _("Conversion to primary energy of fuel mix"),
	"CO2ConvFuelMix" : _("Specific CO2 emission of fuel mix"),
	"PEConvFuelCHP" : _("Conversion to primary energy of fuel mix"),
	"CO2ConvFuelCHP" : _("Specific CO2 emission of fuel mix"),
	"FuelTariffMix" : _("Mean tariff of the fuel mix"),
	"FuelTariffCHP" : _("Fuel tariff for CHP"),
	"Equipment" : _("Short name of equipment"),
	"Manufact" : _("Manufacturer"),
	"YearManufact" : _("Year of  manufacturing or/and installation?"),
	"Model" : _("Model"),
	"EquipType" : _("Type of equipment"),
	"NumEquipUnits" : _("Number of units of the same type"),
	"FuelType" : _("Fuel type"),
	"HCGPnom" : _("Nominal power (heat or cold, output)"),
	"FuelConsum" : _("Fuel consumption (nominal)"),
	"UnitsFuelConsum" : _("Units (fuel consumption)"),
	"ElectriConsum" : _("Electrical power input"),
	"HCGTEfficiency" : _("Mean overall thermal conversion efficiency"),
	"TExhaustGas" : _("Temperature of exhaust gas at standard operation conditions"),
	"ExcessAirRatio" : _("Excess air ratio"),
	"PartLoad" : _("Mean utilisation factor (full capacity = 100%)"),
	"HPerDayEq" : _("Hours of operation per day"),
	"NDaysEq" : _("Days of operation per year"),
	"USHtotQ" : _("Useful Supply Heat from questionnaire"),
	"PipeDuctEquip" : _("Heat or cold supplyed to the distribution line / branch (piping or duct) no."),
	"CHP only" : _("0"),
	"ElectriProduction" : _("Electricity production"),
	"HCGEEfficiency" : _("Electrical conversion efficiency"),
	"Heat pumps only" : _("Heat pumps only:"),
	"HeatSourceLT" : _("Low temperature heat source"),
	"THeatSourceLT " : _("Temperature of heat source"),
	"Thermal heat pumps" : _("Heat pumps only:"),
	"ThermalConsum" : _("Thermal power input  (thermal heat pumps only)"),
	"THeatSourceHT  " : _("Driving temperature (thermal heat pumps only)"),
	"HeatSourceHT" : _("Origin of high temperature heat source (thermal heat pumps only)"),
	"Cold generation only" : _("0"),
	"Refrigerant" : _("Refrigerant"),
	"ThermalConsum" : _("Thermal power input"),
	"THeatSourceHT  " : _("Driving temperature"),
	"HeatSourceHT" : _(" Origin of high temperature heat source"),
	"DestinationWasteHeat" : _("Destination of waste heat"),
	"TemperatureReCooling" : _("Temperature of re-cooling"),
	"CoolTowerType" : _("Only for cooling: type of cooling tower: dry/wet ?"),
	"NEquip" : _("Number of supply equipments"),
	"USH" : _("Useful Supply Heat for industry (total)"),
	"USHj" : _("Useful Supply Heat by equipment"),
	"FET" : _("Final Energy consumption for Thermal use for industry (total)"),
	"FETj" : _("Final energy consumed by the equipment"),
	"QHXEqTotal" : _("Useful Supply Heat for industry (total)"),
	"QHXEq" : _("Waste heat input (equipment)"),
	"QWHEq" : _("Waste heat output (exhaust gas, waste heat fr. heat pumps, ...)"),
	"HGEffAvg" : _("Average conversion efficiency from final energy to useful supply heat"),
	"FlowExhaustGas" : _("Exhaust gas flow rate"),
	"QExhaustGas " : _("Energy content in exhaust gas"),
	"HPerYearEq " : _("Yearly operating hours of equipment = HperDayEq*NDaysEq"),
	"EqNo" : _("Consecutive numbering of equipments in the system"),
	"CascadeIndex" : _("Index of equipment in heat supply cascade"),
	"HXName" : _("Short name of heat exchanger"),
	"HXType" : _("Heat exchanger type"),
	"QdotHX" : _("Heat transfer rate"),
	"HXLMTD" : _("Log. Mean Temperature Diff. (LMTD)"),
	"QHX" : _("Total heat transfered"),
	"HXSourceInlet" : _("Heat source (process [+outflow no.], equipment, ...)"),
	"HXTSourceInlet" : _("Inlet temperature (source)"),
	"HXhSourceInlet  " : _("Inlet specific enthalpy (source)"),
	"HXTSourceOutlet" : _("Outlet temperature (source)"),
	"HXhSourceOutlet    " : _("Outlet specific enthalpy (source)"),
	"HXSink" : _("Heat sink (process, pipe/duct)"),
	"HXTSinkInlet" : _("Inlet temperature (sink)"),
	"HXTSinkOutlet" : _("Outlet temperature (sink)"),
	"WHEEName" : _("Short name of electrical equipment"),
	"WHEEEqType" : _("Equipment type"),
	"WHEEWasteHeatType" : _("Waste heat type"),
	"QWHEE" : _("Available waste heat"),
	"WHEEMedium" : _("Medium"),
	"WHEEFlow" : _("Flow rate"),
	"WHEETOutlet" : _("waste heat temperature"),
	"WHEEPresentUse" : _("present use of waste heat"),
	"'----" : _("Schedule"),
	"HPerDayWHEE " : _("hours of  operation per day"),
	"NBatchWHEE " : _("number of batches per day"),
	"HBatchWHEE " : _("duration of 1 batch"),
	"NDaysWHEE " : _("days of process operation per year"),
	"PipeDuct" : _("name of the branch / distribution system"),
	"HeatSource(s)" : _("heat or cold supply comes from (HX or equipment) No.:"),
	"HeatDistMedium" : _("heat or cold distribution medium"),
	"DistribCircFlow" : _("nominal production or circulation rate (specify units)"),
	"UnitsDistribCircFlow" : _("Units (of nominal production or circulation rate)"),
	"ToutDistrib" : _("outlet temperature (to distribution)"),
	"TreturnDistrib" : _("return temperature (from distribution)"),
	"PercentRecirc" : _("Percentage of recirculation"),
	"Tfeedup" : _("feed-up in open circuit"),
	"PressDistMedium" : _("pressure of heat or cold distribution medium"),
	"TotLengthDistPipe" : _("total length of distribution piping or ducts (one way)"),
	"UAPipe" : _("total coefficient of heat losses for piping or ducts"),
	"DDistPipe" : _("mean pipe diameter"),
	"DeltaDistPipe" : _("insulation thickness"),
	"NumStorageUnits" : _("number of the storage units "),
	"VtotStorage" : _("volume of the storage"),
	"TypeStorage" : _("type of heat storage"),
	"PmaxStorage" : _("pressure of heat storage medium"),
	"TmaxStorage" : _("maximum temperature of the storage "),
	"EnclChartHCDistribSys" : _("Enclosing flowchart of the heat supply and distribution system?"),
	"NPipeDuct " : _("Number of pipes or ducts"),
	"PipeDuctNo" : _("name of the branch / distribution system"),
	"HDEffAvg" : _("Average distribution efficiency"),
	"QHXPipe" : _("Waste heat input to the pipe"),
	"QWHPipe" : _("Waste heat output from circuit (E.g. Not directrly returned condensate)"),
	"HPerYearPipe " : _("Annual hours of operation of the pipe (relevant time for calculation of thermal losses)"),
	"NBuild" : _("0"),
	"BuildName" : _("Building short name"),
	"BuildConstructSurface" : _("Constructed surface "),
	"BuildUsefulSurface" : _("Useful surface "),
	"BuildUsage" : _("Use of the building"),
	"BuildEnergyDemand" : _("Global data on energy demand"),
	"BuildMaxHP" : _("Maximum heating power"),
	"BuildMaxCP" : _("Maximum cooling power"),
	"BuildAnnualHeating" : _("Annual heating demand"),
	"BuildAnnualAirCond" : _("Annual demand of air conditioning"),
	"BuildDailyDHW" : _("Daily consumption of  DHW"),
	"BuildHoursOccup" : _("Hours of occupation "),
	"BuildDaysInUse" : _("Days of use per year"),
	"BuildHolidaysPeriod" : _("Holidays period"),
	"BuildHeatingPeriod" : _("Heating period"),
	"BuildAirCondPeriod" : _("Air conditioning period"),
	"EnclBuildDraw" : _("Enclosing building drawing or sketch?"),
	"REMotivation" : _("Main motivation for renewable energy use"),
	"REInterest" : _("Are you interested in the use of renweable energy? (solar thermal/biomass)"),
	"REReason" : _("If affirmative, please specify the principal reasons:"),
	"text for Quest., value of REReason " : _(" possibility of saving fuel cost"),
	"text for Quest., value of REReason " : _(" contribution to a more ecologic energy supply"),
	"text for Quest., value of REReason " : _("using solar energy helps for a better marketing of your products"),
	"text for Quest., value of REReason " : _("others: "),
	"SurfAreaRoof" : _("Available roof area"),
	"SurfAreaGround" : _("Available ground area"),
	"InclinationRoof" : _("Positioning of the roof area"),
	"InclinationGround" : _("Positioning of the ground area"),
	"OrientationRoof" : _("Orientation of roof (to south)"),
	"OrientationGround" : _("Orientation of ground (to south)"),
	"ShadingRoof" : _("shading of roof"),
	"ShadingGround" : _("shading of ground"),
	"DistanceToRoof" : _("Distance between roof and process"),
	"DistanceToGround" : _("Distance between ground and process"),
	"RoofType" : _("type of roof"),
	"RoofStaticLoadCap" : _("static load capacity of the roof(s)"),
	"EnclBuildGroundSketch" : _("Enclosing of drawing or scheme of building?"),
	"BiomassFromProc" : _("Type of biomass available from processes"),
	"PeriodBiomassProcStart" : _("Period of year the biomass is available - start"),
	"PeriodBiomassProcStop" : _("Period of year the biomass is available - stop"),
	"NDaysBiomassProc" : _("Number of days biomass is produced"),
	"QBiomassProcDay" : _("Daily quantity of biomass"),
	"SpaceBiomassProc" : _("Space availability to stock biomass?"),
	"LCVBiomassProc" : _("LCV biomass"),
	"HumidBiomassProc" : _("Humidity"),
	"BiomassFromRegion" : _("Type of biomass available "),
	"PriceBiomassRegion" : _("Unit price of biomass"),
	"PeriodBiomassRegionStart" : _("Period of year the biomass is available - start"),
	"PeriodBiomassRegionStop" : _("Period of year the biomass is available - stop"),
	"NDaysBiomassRegion" : _("Number of days the biomass is produced"),
	"InflationRate" : _("General inflation rate"),
	"FuelPriceRate" : _("Rate of increment of energy prices"),
	"InterestExtFinancing" : _("Nominal rate of interest for external financing of installations "),
	"PercentExtFinancing" : _("Percentage of external financing for installations"),
	"AmortisationTime" : _("Time for economic amortisation of installations"),
	"PublicFundType" : _("Type (credit, subvention)"),
	"OMGenTot" : _("General maintenance - total costs"),
	"OMGenOP" : _("General maintenance - own personnel"),
	"OMGenEP" : _("General maintenance - external personnel"),
	"OMGenFung" : _("General maintenance - fungible assets"),
	"OMBuildTot" : _("Buildings - total costs"),
	"OMBuildOP" : _("Buildings - own personnel"),
	"OMBuildEP" : _("Buildings - external personnel"),
	"OMBiuildFung" : _("Buildings - fungible assets"),
	"OMMachEquipTot" : _("Machines and equipment - total costs"),
	"OMMachEquipOP" : _("Machines and equipment - own personnel"),
	"OMMachEquipEP" : _("Machines and equipment  - external personnel"),
	"OMMachEquipFung" : _("Machines and equipment  - fungible assets"),
	"OMHCGenDistTot" : _("Generation and distribution of heat and cold - total costs"),
	"OMHCGenDistOP" : _("Generation and distribution of heat and cold - own personnel"),
	"OMHCGenDistEP" : _("Generation and distribution of heat and cold  - external personnel"),
	"OMHCGenDistFung" : _("Generation and Distribution of heat and cold  - fungible assets"),
	"OMTotalTot" : _("Total - total costs"),
	"OMTotalOP" : _("Total - own personnel"),
	"OMTotalEP" : _("Total - external personnel"),
	"OMTotalFung" : _("Total - fungible assets"),
	"EnergyManagExisting" : _("Is there any energy menagement system implemented?"),
	"EnergyManagExternal" : _("Is the energy menagent externalized?"),
	"General energetic and environmental conversion parameters" : _("0"),
	"PEConvEl" : _("Conversion to primary energy of electricity"),
	"CO2ConvEl" : _("Specific CO2 emission of electricity"),
	"HRInvRate" : _("Specific investment cost for heat recovery system"),
	"HROMRate" : _("Specific annual O&M cost for heat recovery system"),
	"FeedInCHP" : _("Feedin Tariff for CHP Electricity"),
	"SolarInvRateL" : _("Specific turn-key installation cost large systems ( > 1 MW)"),
	"SolarInvRateS" : _("Specific turn-key installation cost small systems (< 10 kW)"),
	"SolarOMRate" : _("specific yearly O&M costs"),
	"SolarFunding" : _("Percentage of public funding"),
	"QuSolar" : _("Specifc solar useful heat production"),
	"Economic parameters" : _("0"),
	"Inflation" : _("Inflació general"),
	"InflationFuels" : _("Increment previst preu de combustible (nominal)"),
	"InterestRate" : _("Interest rate for external financing"),
	"ExternalFinance" : _("Percentage of external financing"),
	"Amortisation" : _("Amortisation period"),
	"Annuity" : _("Annuity of investment"),
	"EEFunding" : _("Public funding for energy saving measures"),
	"Heat pump module" : _("0"),
	"MaintainExisting" : _("Maintain existing equipment"),
	"Boiler module" : _("0"),
	"Solar thermal module" : _("0"),
	"Chiller module" : _("0"),
	"PE_INT_BML" : _("benchmark (lower limit)"),
	"PE_INT_BMH" : _("benchmark (upper limit)"),
	"PE_INT_TAR" : _("target"),
	"PE_INT_REF" : _("reference code selected benchmark and target"),
	"EL_INT_BML" : _("benchmark (lower limit)"),
	"EL_INT_BMH" : _("benchmark (upper limit)"),
	"EL_INT_TAR" : _("target"),
	"EL_INT_REF" : _("reference code selected benchmark and target"),
	"FUEL_INT_BML" : _("benchmark (lower limit)"),
	"FUEL_INT_BMH" : _("benchmark (upper limit)"),
	"FUEL_INT_TAR" : _("target"),
	"FUEL_INT_REF" : _("reference code selected benchmark and target"),
	"PE_SEC_BML" : _("benchmark (lower limit)"),
	"PE_SEC_BMH" : _("benchmark (upper limit)"),
	"PE_SEC_TAR" : _("target"),
	"PE_SEC_REF" : _("reference code selected benchmark and target"),
	"EL_SEC_BML" : _("benchmark (lower limit)"),
	"EL_SEC_BMH" : _("benchmark (upper limit)"),
	"EL_SEC_TAR" : _("target"),
	"EL_SEC_REF" : _("reference code selected benchmark and target"),
	"FUEL_SEC_BML" : _("benchmark (lower limit)"),
	"FUEL_SEC_BMH" : _("benchmark (upper limit)"),
	"FUEL_SEC_TAR" : _("target"),
	"FUEL_SEC_REF" : _("reference code selected benchmark and target"),
	"PE_UOS_BML" : _("benchmark (lower limit)"),
	"PE_UOS_BMH" : _("benchmark (upper limit)"),
	"PE_UOS_TAR" : _("target"),
	"PE_UOS_REF" : _("reference code selected benchmark and target"),
	"EL_UOS_BML" : _("benchmark (lower limit)"),
	"EL_UOS_BMH" : _("benchmark (upper limit)"),
	"EL_UOS_TAR" : _("target"),
	"EL_UOS_REF" : _("reference code selected benchmark and target"),
	"UPHS_BML" : _("benchmark (lower limit)"),
	"UPHS_BMH" : _("benchmark (upper limit)"),
	"UPHS_TAR" : _("target"),
	"UPHS_REF" : _("reference code selected benchmark and target"),
	"ENE_INT_CHK" : _("evaluation of energy intensity"),
	"ENE_INT_COM" : _("comment on evaluation of energy intensity"),
	"ENE_SEC_CHK" : _("evaluation of energy intensity"),
	"ENE_SEC_COM" : _("comment on evaluation of energy intensity"),
	"ENE_UOS_CHK" : _("evaluation of energy intensity"),
	"ENE_UOS_COM" : _("comment on evaluation of energy intensity"),
	"STOOL: General state of processing" : _("Conversion to primary energy of electricity"),
	"StatusQ" : _("0"),
	"StatusCC" : _("Industry data have been checked for consistency, and no modification of data has been done since last consistency check"),
	"StatusCS" : _("0"),
	"StatusR" : _("0"),
	"LanguageReport" : _("0"),
	"UnitsReport" : _("0"),
	"ActiveAlternative" : _("Number of alternative actually under processing"),
	"NoOfAlternatives" : _("Total number of alternatives"),
	"FinalAlternative" : _("-1: no selection carried out yet. 0: no improvements with respect to present state possible n: number of selected (best) alternative"),
	"WriteProtected" : _("True if project has been write protected (e.g. Final version for back-up)"),
	"SALTERNATIVES: State of processing of a given alternative" : _("0"),
	"ShortName" : _("ShortName of the alternative"),
	"Description" : _("Description of the alternative"),
	"StatusA" : _("Design of alternative fully concluded?"),
	"StatusPO" : _("0"),
	"StatusPI" : _("0"),
	"StatusHX" : _("0"),
	"StatusHC" : _("Some variable(s) indicating the state of design of the different sub-systems (HP, Boilers, ST, ...)"),
	"StatusEnergy" : _("Energy calculation concluded"),
	"StatusECO" : _("Economic calculation concluded"),
	"STOOL:Backup general tool interface settings (not project specific !!!)" : _("0"),
	"UserInteractionLevel" : _("Level of user interaction"),
	"LanguageTool" : _("0"),
	"UnitsTool" : _("0"),
	"UserType        " : _("# type of user: expert, student, end-user ... ???"),
	"ActiveProject" : _("Pointer to Pid that last has been processed"),
	"Name" : _("name of the auditor"),
	"City" : _("city"),
	"Country" : _("country"),
	"Company" : _("name of the company"),
	"CompanyType" : _("type of company (consultancy, ...)"),
	"Address" : _("address"),
	"Phone" : _("Telephone  No"),
	"Fax" : _("Fax No"),
	"Email" : _("E-mail"),
	"web" : _("web site"),
	"dummy":"dummy"
}
