-- update einstein database
USE einstein;

-- update dbheatpump
ALTER TABLE dbheatpump ADD COLUMN Reference VARCHAR(200) DEFAULT NULL AFTER HPSubType;
ALTER TABLE dbheatpump DROP DBFuel_id;
ALTER TABLE dbheatpump ADD COLUMN FuelType VARCHAR(45) DEFAULT NULL AFTER HPCoolCOP;
ALTER TABLE dbheatpump CHANGE HPAbsEffects HPSourceSink VARCHAR(45) DEFAULT NULL;
ALTER TABLE dbheatpump DROP HPYearManufact;
ALTER TABLE dbheatpump DROP HPUnitsFuelConsum;
ALTER TABLE dbheatpump DROP HPManData;

-- update dbchp
ALTER TABLE dbchp ADD COLUMN Manufacturer VARCHAR(200) DEFAULT NULL;
ALTER TABLE dbchp ADD COLUMN Type VARCHAR(45) DEFAULT NULL AFTER CHPequip;
ALTER TABLE dbchp ADD COLUMN SubType VARCHAR(45) DEFAULT NULL AFTER Type;
ALTER TABLE dbchp ADD COLUMN Reference VARCHAR(200) DEFAULT NULL AFTER SubType;
ALTER TABLE dbchp ADD COLUMN FuelType VARCHAR(45) DEFAULT NULL AFTER CHPPt;
ALTER TABLE dbchp ADD COLUMN FluidSupply double DEFAULT NULL AFTER Eta_e;
ALTER TABLE dbchp ADD COLUMN Tsupply double DEFAULT NULL AFTER FluidSupply;
ALTER TABLE dbchp ADD COLUMN FlowRateSupply double DEFAULT NULL AFTER Tsupply;
ALTER TABLE dbchp ADD COLUMN FluidSupply2 double DEFAULT NULL AFTER FlowRateSupply;
ALTER TABLE dbchp ADD COLUMN Tsupply2 double DEFAULT NULL AFTER FluidSupply2;
ALTER TABLE dbchp ADD COLUMN FlowRateSupply2 double DEFAULT NULL AFTER Tsupply2;
ALTER TABLE dbchp ADD COLUMN Price double DEFAULT NULL AFTER FlowRateSupply2;
ALTER TABLE dbchp ADD COLUMN YearUpdate double DEFAULT NULL AFTER OMRateVar;
